@startuml BloquimDiagramaClasse

class loginController{
    -usuario: String
    -senha : String  

    + irCadastro() : void
    # verificaSenha() : void 
    + completaLogin() : void
}
class cadastroController{
    -usuario: String
    -senha : String  
    -email : String

    + realizaCadastro() : void
    # verificaSenha() : void 
    + realizaCadastro() : void
}


class anotacaoController{
    + conteudo : String
    - anotacoes : String
    + dataModificacao : String

    + marcacoes() : void
    + adicionaAnotacoes() : void
}

class caderno{
    + nome : String 
    - <Anotacoes> : list
    + dataCriacao : int 
    + dataModificacao : int 

}

class controllerCadernoNormal{

    + disciplina : String
    + capitulos : String 


    + inserirCadernos() : void
}

class controllerCadernoDiario{

    + humorDoDia : int

    # verificarCondicoesParaInserirCaderno() : boolean 
    + inserirAnotacoes() : void 
}

loginController "1" -- "0.."caderno:Entra no >
controllerCadernoNormal  "1.." -- "1.." anotacaoController : < Pertence à 
controllerCadernoDiario "1.." -- "1.." anotacaoController : < Pertence à
caderno "1" -- "1.." controllerCadernoNormal : < É um tipo
caderno "1" -- "1.." controllerCadernoDiario : < É um tipo

@enduml